### ISSUE TITLE
Remote execution TODO

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/thingengine-core#8]
- [x] some hack for queries with multiple results in commands
- [x] auto destruction for rules
- [x] metadata-based formatting
- [x] separate local/remote confirmations
- [x] identity lookups for confirmations
- [x] proper deferred execution
- [x] replace "$remote" in app names
- [x] more testing
- [x] Android support
- [x] deferred slot filling

**Comment by gcampax** [comment]
DONE and submitted to Ubicomp!
